spring:
  application:
    name: board
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/board
    username: root
    password: fkqlzjxj7831!
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

logging:
  level:
    jdbc:
      sqlonly: info
      sqltiming: off
      audit: off
      resultsettable: info
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml